CREATE SEQUENCE SEQ_PERSON_ID;

CREATE TABLE PERSON(ID INT PRIMARY KEY, NAME VARCHAR(255), BORN_DATE  VARCHAR(10));

INSERT INTO PERSON (ID, NAME, BORN_DATE) VALUES ( 1, 'AGNALDO F. ANJOS', '1972-10-08');
INSERT INTO PERSON (ID, NAME, BORN_DATE) VALUES ( 2, 'MIGUEL M. ANJOS', '2004-01-31');
INSERT INTO PERSON (ID, NAME, BORN_DATE) VALUES ( 3, 'GUABRIEL M. ANJOS', '2007-07-28');
