server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret
info:
  app-name:Sample with postgres
